version: "3.8"
services:
  users-register:
    build:
      context: ./users-register
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://matank222:ElzWhd3CUam4K8iw@library.l5ntd.mongodb.net/?retryWrites=true&w=majority&appName=library
    networks:
      - app-network

  users-delete:
    build:
      context: ./users-delete
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb+srv://matank222:ElzWhd3CUam4K8iw@library.l5ntd.mongodb.net/?retryWrites=true&w=majority&appName=library
    networks:
      - app-network

  books-add:
    build:
      context: ./books-add
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb+srv://matank222:ElzWhd3CUam4K8iw@library.l5ntd.mongodb.net/?retryWrites=true&w=majority&appName=library
    networks:
      - app-network

  books-borrow:
    build:
      context: ./books-borrow
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    environment:
      - MONGO_URI=mongodb+srv://matank222:ElzWhd3CUam4K8iw@library.l5ntd.mongodb.net/?retryWrites=true&w=majority&appName=library
    networks:
      - app-network

  books-return:
    build:
      context: ./books-return
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    environment:
      - MONGO_URI=mongodb+srv://matank222:ElzWhd3CUam4K8iw@library.l5ntd.mongodb.net/?retryWrites=true&w=majority&appName=library
    networks:
      - app-network

  books-rate:
    build:
      context: ./books-rate
      dockerfile: Dockerfile
    ports:
      - "5006:5006"
    environment:
      - MONGO_URI=mongodb+srv://matank222:ElzWhd3CUam4K8iw@library.l5ntd.mongodb.net/?retryWrites=true&w=majority&appName=library
    networks:
      - app-network

  books-rate-alt:
    build:
      context: ./books-rate-alt
      dockerfile: Dockerfile
    ports:
      - "5009:5009"
    environment:
      - MONGO_URI=mongodb+srv://matank222:ElzWhd3CUam4K8iw@library.l5ntd.mongodb.net/?retryWrites=true&w=majority&appName=library
    networks:
      - app-network

  books-search:
    build:
      context: ./books-search
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - MONGO_URI=mongodb+srv://matank222:ElzWhd3CUam4K8iw@library.l5ntd.mongodb.net/?retryWrites=true&w=majority&appName=library
    networks:
      - app-network
  books-search-alt:
    build:
      context: ./books-search-alt
      dockerfile: Dockerfile
    ports:
      - "5008:5008"
    environment:
      - MONGO_URI=mongodb+srv://matank222:ElzWhd3CUam4K8iw@library.l5ntd.mongodb.net/?retryWrites=true&w=majority&appName=library
    networks:
      - app-network

  reports-basic:
    build:
      context: ./reports-basic
      dockerfile: Dockerfile
    ports:
      - "5007:5007"
    environment:
      - MONGO_URI=mongodb+srv://matank222:ElzWhd3CUam4K8iw@library.l5ntd.mongodb.net/?retryWrites=true&w=majority&appName=library
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
