version: "3.8"
services:
  users-register:
    build:
      context: ./users-register
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://matank222:ElzWhd3CUam4K8iw@library.l5ntd.mongodb.net/?retryWrites=true&w=majority&appName=library
    networks:
      - app-network
  users-delete:
    build:
      context: ./users-delete
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb+srv://matank222:ElzWhd3CUam4K8iw@library.l5ntd.mongodb.net/?retryWrites=true&w=majority&appName=library
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
